### ISSUE TITLE
Prettier python_requires

### ISSUE THREAD

**Issue by mgedmin** [mgedmin/check-python-versions#10]
Some people (*cough* jamadden *cough*) format python_requires like this:

```python
    python_requires=', '.join([
        '>= 2.7',
        '!= 3.0',
        '!= 3.1',
        '!= 3.2',
        '!= 3.3',
        '!= 3.4',
    ])
```

check-python-versions is able to parse this, but when modifying it overwrites it with a one-line expression

```python
    python_requires='>= 2.7, != 3.0, != 3.1, != 3.2, != 3.3, != 3.4',
```

(actually it's buggy and replaces the first line, then leaves the rest in place, introducing a syntax error!)

It would be nice if it could preserve the multiline formatting.

**Comment by jamadden** [comment]
I copied that from someone, I think icemac.
