### ISSUE TITLE
Does not support `~=` operator in python_requires

### ISSUE THREAD

**Issue by nvllsvm** [mgedmin/check-python-versions#2]
The `~=` operator is commonly used to pin to a major and minor version while allowing any patch version. Ex. `python_requires='~=2.7'` works for Python 2.7.0 up to the latest 2.7.15.

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by mgedmin** [comment]
Thank you for the bug report!

I don't have the energy to implement the full spec, but I'm happy to swat at the specific examples that do not currently work as users complain about them.

**Comment by mgedmin** [comment]
check-python-versions 0.11.0 is released with a fix for this (that does implement a full PEP-440 spec).

I would not be surprised to hear it has bugs.  Eagerly awaiting testers!
