### ISSUE TITLE
Does not handle new PyPy versions notations for GHA correctly

### ISSUE THREAD

**Issue by icemac** [mgedmin/check-python-versions#24]
This came up in: https://github.com/zopefoundation/zope.publisher/pull/58#issuecomment-747991306

There are new variants to request a specific PyPy version on GHA which are currently not recognized by the checker as valid PyPy versions.

**Comment by mgedmin** [comment]
It would be helpful if I could see what the YAML looks like.

**Comment by mgedmin** [comment]
Ok, as far as I understand, there was a new release of `actions/setup-python`, version 2.2.0, which moved the `v2` tag (yay!  aren't git tags supposed to be unchanging?).  This release extended the Python version syntax to allow `pypy-X.Y` and `pypy-X.Y-vA.B.C`, and it also included a regression where the old `pypy2`/`pypy3` versions [stopped working](https://github.com/actions/setup-python/issues/171).

Later there was a v2.2.1 release (which moved the `v2` tag again), and now all syntaxes work fine.

check-python-versions supports only the old `pypyX` syntax and needs to be extended to support `pypy-X.Y[-vA.B.C]`.

**Comment by mgedmin** [comment]
Ok, this should be fixed now.

Apologies for the inconvenience!

**Comment by icemac** [comment]
Thank you for looking into this issue. 😀
