### ISSUE TITLE
Package supporting PyPy is not enforced to test for it

### ISSUE THREAD

**Issue by icemac** [mgedmin/check-python-versions#26]
In https://github.com/zopefoundation/zope.app.folder/pull/2 I accidentally configured the package not to test PyPy even though `setup.py` says that PyPy is supported. (See https://github.com/zopefoundation/zope.app.folder/pull/2/commits/91ecf540dfff7efe5f4e8fd6d51c6d97efc5f75e, fixed in https://github.com/zopefoundation/zope.app.folder/pull/2/commits/9c87598dcccff979ddf3fbd7691222ff3cac38f7)

The relevant part of the `lint` tox environment run looks like this:

```
lint run-test: commands[2] | check-python-versions
setup.py says:                    2.7, 3.5, 3.6, 3.7, 3.8, 3.9, PyPy
tox.ini says:                     2.7, 3.5, 3.6, 3.7, 3.8, 3.9
.github/workflows/tests.yml says: 2.7, 3.5, 3.6, 3.7, 3.8, 3.9
_______________________________ summary _________________________________
  lint: commands succeeded
```

I would have expected the call to fail because PyPy support is declared but not tested anywhere.

**Comment by mgedmin** [comment]
The current behavior is [documented](https://github.com/mgedmin/check-python-versions/blob/master/README.rst#python-versions)

> These extra Pythons are shown, but not compared for consistency.

but maybe it's time to change that.

How about this:

- setup.py currently can't detect PyPy3, but we can change the logic to assume PyPy iff it has the Implementation :: PyPy classifier and any Python :: 2 classiifier; likewise PyPy3 can be inferred if there's both Implementation :: PyPy and any Python :: 3 classifier.
- tox.ini, .travis.yml and .github/workflows/\*.yml already detect PyPy / PyPy3 (and I need to update the README to mention github actions in the Python versions section, and also note that 3.9, not 3.8 is the latest current release.)
- python_requires, appveyor and manylinux will be excluded from PyPy consistency checks
- other custom interpreters (Jython, IronPython etc) are out of scope

?  This seems doable.

**Comment by icemac** [comment]
@mgedmin Thank you for giving this issue a chance. I absolutely like your proposal.

**Comment by mgedmin** [comment]
I have to say output like

```
setup.py says:                    3.6, 3.7, 3.8, 3.9, PyPy3
- python_requires says:           3.6, 3.7, 3.8, 3.9
tox.ini says:                     3.6, 3.7, 3.8, 3.9
.travis.yml says:                 3.6, 3.7, 3.8, 3.9, PyPy3
.github/workflows/build.yml says: 3.6, 3.7, 3.8, 3.9, PyPy3
appveyor.yml says:                3.6, 3.7, 3.8, 3.9

mismatch!
```

is a bit suboptimal: it's unclear where the mismatch is.

(It's missing pypy3 in tox.ini in this case -- python_requires does not normally constrain implementations, and I don't know how to do PyPy in Appveyor and I have no plans to research that question.)

I wonder if I could make check-python-versions say what the mismatch is.

**Comment by mgedmin** [comment]
Would you like to test this feature from git master before I cut a new release?

**Comment by icemac** [comment]
Hi @mgedmin, thank you for tackling my issue. I tried the git master on `zope.app.file` where I removed `pypy` and `pypy3` from the `tox.ini`. The result looks like this:

```
setup.py says:                    2.7, 3.5, 3.6, 3.7, 3.8, 3.9, PyPy, PyPy3
tox.ini says:                     2.7, 3.5, 3.6, 3.7, 3.8, 3.9
.github/workflows/tests.yml says: 2.7, 3.5, 3.6, 3.7, 3.8, 3.9, PyPy, PyPy3

mismatch!
```

This is perfectly fine.
I am looking forward to the release of this feature.

**Comment by mgedmin** [comment]
check-python-versions 0.18.0 is out.

**Comment by icemac** [comment]
Thank you! 🎉

**Comment by Wooble** [comment]
By the way, the docs currently say pypy isn't detected in appveyor.yml. It does seem to be detected, although when it's not it doesn't cause the checks to fail. (This seems reasonable, considering it's still not particularly easy to actually use pypy on appveyor; just the wording of the docs is slightly off.)
