### ISSUE TITLE
Name of the `envlist` / `env_list` section in `tox`

### ISSUE THREAD

**Issue by eumiro** [mgedmin/check-python-versions#42]
According to https://tox.wiki/en/latest/config.html#env_list both `envlist` and `env_list` are possible.

When running the latest version of `check-python-versions` within `pre-commit`, it cannot read the `env_list` section in my `tox.ini` file (it says `(empty)` and expects `envlist`. This conflicts with `tox-ini-fmt` that rejects `envlist` and suggests `env_list`. As result, I cannot write single name of the section to satisfy both plugins.

To be fair, I am writing this issue to both projects (https://github.com/tox-dev/tox-ini-fmt/issues/160), but it would be nice if both alternatives were accepted. Would you like a PR?

**Comment by eumiro** [comment]
According to https://github.com/tox-dev/tox-ini-fmt/issues/160#issuecomment-1606230881 this looks like we should stick with `env_list` here as well.

**Comment by mgedmin** [comment]
Thank you for bringing this to my attention, I'd no idea!

**Comment by eumiro** [comment]
Thank you, it works now. Would it make sense to report/warn the user if they use `envlist` instead of `env_list`?
