### ISSUE TITLE
Error when checking ZODB project

### ISSUE THREAD

**Issue by jugmac00** [mgedmin/check-python-versions#6]
I get an error message using your tool - but only on ZODB - other projects work... 

I installed it with `pipx`.

```
ZODB on  add-py38 [!] via 🐍 v2.7.15+ 
❯ check-python-versions 
Non-literal classifiers= passed to setup()
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
setup.py says:              (empty)
- python_requires says:     2.7, 3.5, 3.6, 3.7, 3.8
tox.ini says:               2.7, 3.5, 3.6, 3.7, 3.8, PyPy, PyPy3
.travis.yml says:           2.7, 3.5, 3.6, 3.7, 3.8, PyPy, PyPy3
appveyor.yml says:          2.7, 3.5, 3.6, 3.7, 3.8

mismatch!
```

**Comment by mgedmin** [comment]
What's happening here is check-python-version tries to parse setup.py using the AST, sees that classifiers [is not a constant literal](https://github.com/zopefoundation/ZODB/blob/e96448d248fa6c8d23d360db5b976fb14bd286a6/setup.py#L63), then falls back to running

    python setup.py -q --classifiers

The traceback you see is printed by that command (because the `python` in your $PATH does not have setuptools available).

I could maybe use `sys.executable` instead of `python`, which would make check-python-versions use the interperter from the pipx-created venv, but I don't want to do that for reasons:
- the user gets less chance to influence what python to use
- it would only work on packages that already support Python 3.6+

I could maybe improve the error message here (e.g. I'm not currently capturing stderr at all).

Thoughts?

**Comment by jugmac00** [comment]
Thank you for the detailed explanation.

On a gut level, without thinking too much... what about including `setuptools` in `install_requires`?

**Comment by mgedmin** [comment]
Including setuptools in check-python-versions's install_requires would help only if I used [sys.executable, 'setup.py', '-q', '--classifiers'].

**Comment by jugmac00** [comment]
I have to admit I would have to invest way more time to understand what is going on here... 

So instead, I played around with manually creating a virtualenv, installing your tool, symlinking into my path... still does not work.

```
~/Virtualenvironments/check-python-versions 
❯ bin/pip freeze
check-python-versions==0.13.0
pkg-resources==0.0.0
PyYAML==5.1.2

~/Virtualenvironments/check-python-versions 
❯ bin/pip install setuptools
Requirement already satisfied: setuptools in ./lib/python3.8/site-packages (39.0.1)
```

The last thing I could image was to setup a virtualenv with system-site-packages... and whoops, it works!

```
~/Virtualenvironments/test-with-sys 
❯ python3.8 -m venv . --system-site-packages

~/Virtualenvironments/test-with-sys took 9s 
❯ bin/pip install check-python-versions
Collecting check-python-versions
  Using cached https://files.pythonhosted.org/packages/93/00/65858147d44f3e6e5a32319daba7005f31cb28c176113d1f34d840357556/check_python_versions-0.13.0-py2.py3-none-any.whl
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from check-python-versions)
Installing collected packages: check-python-versions
Successfully installed check-python-versions-0.13.0

~/Virtualenvironments/test-with-sys 
❯ which check-python-versions
/home/jugmac00/Virtualenvironments/test-with-sys/bin/check-python-versions

~/Virtualenvironments/test-with-sys 
❯ check-python-versions ~/Projects/ZODB/
Non-literal classifiers= passed to setup()
setup.py says:              2.7, 3.5, 3.6, 3.7, 3.8, PyPy
- python_requires says:     2.7, 3.5, 3.6, 3.7, 3.8
tox.ini says:               2.7, 3.5, 3.6, 3.7, 3.8, PyPy, PyPy3
.travis.yml says:           2.7, 3.5, 3.6, 3.7, 3.8, PyPy, PyPy3
appveyor.yml says:          2.7, 3.5, 3.6, 3.7, 3.8
```

This whole **setuptools is not available**, but of course you cannot install it, because **it is already there** is quite confusing :-)

**Comment by jugmac00** [comment]
Huh?

The same installation works - but only when the virtualenv is activted.. but does not when deactivated...

```
~/Virtualenvironments/check-python-versions 
❯ check-python-versions ~/Projects/ZODB/
Non-literal classifiers= passed to setup()
setup.py says:              2.7, 3.5, 3.6, 3.7, 3.8, PyPy
- python_requires says:     2.7, 3.5, 3.6, 3.7, 3.8
tox.ini says:               2.7, 3.5, 3.6, 3.7, 3.8, PyPy, PyPy3
.travis.yml says:           2.7, 3.5, 3.6, 3.7, 3.8, PyPy, PyPy3
appveyor.yml says:          2.7, 3.5, 3.6, 3.7, 3.8

~/Virtualenvironments/check-python-versions 
❯ deactivate

~/Virtualenvironments/check-python-versions 
❯ check-python-versions ~/Projects/ZODB/
Non-literal classifiers= passed to setup()
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
setup.py says:              (empty)
- python_requires says:     2.7, 3.5, 3.6, 3.7, 3.8
tox.ini says:               2.7, 3.5, 3.6, 3.7, 3.8, PyPy, PyPy3
.travis.yml says:           2.7, 3.5, 3.6, 3.7, 3.8, PyPy, PyPy3
appveyor.yml says:          2.7, 3.5, 3.6, 3.7, 3.8

mismatch!
```

**Comment by mgedmin** [comment]
> The same installation works - but only when the virtualenv is activted.. but does not when deactivated...

Yes, because the salient thing is which `python` binary is found first on your $PATH.  Activating the virtualenv changes $PATH, not activating it doesn't.

**Comment by mgedmin** [comment]
I'm going to close this, because I don't know what check-python-version could do to handle this situation better.

**Comment by jugmac00** [comment]
I refrain from reading all the comments again, because I already have a headache from debugging PHP scripts on a Windows server.

Thanks for your time anyway!
